// Builds game-html.js, the game page the app loads in its WebView, from
// ../web/index.html. The page is wrapped in a document skeleton (like
// web/build-pages.sh) and the Google Fonts links are swapped for the bundled
// Montserrat, so the game works offline. Runs on npm install and npm start.
import { readFileSync, writeFileSync } from 'node:fs';

const here = new URL('..', import.meta.url);
const source = readFileSync(new URL('../web/index.html', here), 'utf8');
const font = readFileSync(new URL('assets/fonts/montserrat-800-latin.woff2', here)).toString('base64');

const fontLinks = /^<link [^>]*fonts\.(googleapis|gstatic)\.com[^>]*>\n/gm;
if ((source.match(fontLinks) || []).length !== 3) {
  throw new Error('web/index.html: expected the three Google Fonts <link> lines');
}
const fontFace = `<style>
  @font-face { font-family: Montserrat; font-weight: 800; font-display: block;
               src: url(data:font/woff2;base64,${font}) format('woff2'); }
  /* No keyboard in the app: the focus ring would only frame the screen after a tap. */
  html body canvas:focus-visible { outline: none; }
</style>
`;

const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
${fontFace}</head>
<body>
${source.replace(fontLinks, '')}
</body>
</html>
`;

writeFileSync(new URL('game-html.js', here),
  `// Generated by scripts/build-game.mjs from web/index.html. Do not edit.\nexport default ${JSON.stringify(html)};\n`);
console.log(`game-html.js: ${Math.round(html.length / 1024)} KB`);
