extends RefCounted
## Every text the game shows, in Italian and English. Keys are shared with the
## web port (web/index.html), which has the same table.

const LANGS: Array[String] = ["it", "en"]
const SITE_URL := "https://espertini.com"
const SITE_LABEL := "espertini.com"

const TEXT := {
	"it": {
		"lang_name": "ITALIANO",
		"tagline_1": "Tocca a sinistra o a destra per ruotare",
		"tagline_2": "e abbina il colore delle palline",
		"play": "GIOCA",
		"leaderboard": "CLASSIFICA",
		"best": "RECORD  %d",
		"hud_level": "LIVELLO %d",
		"banner_level": "Livello %d",
		"banner_life": "Livello %d  +1 vita",
		"game_over": "GAME OVER",
		"points_level": "PUNTI  ·  LIVELLO %d",
		"new_best": "NUOVO RECORD!",
		"rank": "%d° IN CLASSIFICA",
		"replay": "RIGIOCA",
		"menu": "MENU",
		"paused": "PAUSA",
		"pause_stats": "%d PUNTI  ·  LIVELLO %d",
		"resume": "RIPRENDI",
		"top_local": "I 10 migliori punteggi su questo dispositivo",
		"no_scores": "Ancora nessun punteggio: gioca una partita!",
		"tap_back": "Tocca per tornare al menu",
		"version": "Versione %s",
		"row_level": "liv. %d",
		"name_hint": "Scrivi il tuo nome",
		"settings": "IMPOSTAZIONI",
		"music": "MUSICA",
		"sounds": "SUONI",
		"language": "LINGUA",
		"on": "SÌ",
		"off": "NO",
		"back": "INDIETRO",
		"about": [
			["COME SI GIOCA", [
				"Ruota la figura: ogni pallina deve",
				"toccare il lato del suo colore.",
				"Ogni 10 punti sali di livello.",
				"Ogni 3 livelli arriva un lato in più",
				"e recuperi una vita.",
				"Dopo 5 errori la partita finisce.",
			]],
			["COMANDI", [
				"Tocca a sinistra o a destra per ruotare",
				"Tastiera: frecce oppure A e D",
				"P o Esc pausa  ·  M musica  ·  S suoni",
			]],
			["CREDITI", [
				"Un gioco di Davide Dex Espertini",
				"Fatto con Godot 4: grafica, suoni",
				"e musica sono generati dal codice",
			]],
		],
	},
	"en": {
		"lang_name": "ENGLISH",
		"tagline_1": "Tap left or right to spin",
		"tagline_2": "and match the color of the balls",
		"play": "PLAY",
		"leaderboard": "LEADERBOARD",
		"best": "BEST  %d",
		"hud_level": "LEVEL %d",
		"banner_level": "Level %d",
		"banner_life": "Level %d  +1 life",
		"game_over": "GAME OVER",
		"points_level": "POINTS  ·  LEVEL %d",
		"new_best": "NEW BEST!",
		"rank": "RANKED #%d",
		"replay": "PLAY AGAIN",
		"menu": "MENU",
		"paused": "PAUSED",
		"pause_stats": "%d POINTS  ·  LEVEL %d",
		"resume": "RESUME",
		"top_local": "Top 10 scores on this device",
		"no_scores": "No scores yet: play a game!",
		"tap_back": "Tap to go back to the menu",
		"version": "Version %s",
		"row_level": "lv. %d",
		"name_hint": "Type your name",
		"settings": "SETTINGS",
		"music": "MUSIC",
		"sounds": "SOUNDS",
		"language": "LANGUAGE",
		"on": "ON",
		"off": "OFF",
		"back": "BACK",
		"about": [
			["HOW TO PLAY", [
				"Spin the shape so every ball",
				"hits the side of its own color.",
				"Every 10 points you level up.",
				"Every 3 levels the shape gains a side",
				"and you get a life back.",
				"After 5 misses the game is over.",
			]],
			["CONTROLS", [
				"Tap left or right to spin",
				"Keyboard: arrows or A and D",
				"P or Esc pause  ·  M music  ·  S sounds",
			]],
			["CREDITS", [
				"A game by Davide Dex Espertini",
				"Made with Godot 4: graphics, sounds",
				"and music are generated in code",
			]],
		],
	},
}
